In [3]:
import numpy as np

a=np.arange(0,20)
b=a.reshape(4,5)
a.shape

(20,)

In [ ]:
b[::2,4]

array([ 4, 14])

In [ ]:
b[2,3]=100
b.reshape(20,)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
       100,  14,  15,  16,  17,  18,  19])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
c=np.random.randint(10,51,size=(5,5))
c

array([[19, 29, 36, 44, 17],
       [49, 23, 20, 32, 33],
       [36, 12, 49, 24, 22],
       [21, 48, 12, 20, 36],
       [10, 13, 24, 17, 49]])

In [ ]:
c[:,2]=0
c

array([[19, 29,  0, 44, 17],
       [49, 23,  0, 32, 33],
       [36, 12,  0, 24, 22],
       [21, 48,  0, 20, 36],
       [10, 13,  0, 17, 49]])

In [ ]:
np.mean(c)
np.rot90(c,k=1)

array([[17, 33, 22, 36, 49],
       [44, 32, 24, 20, 17],
       [ 0,  0,  0,  0,  0],
       [29, 23, 12, 48, 13],
       [19, 49, 36, 21, 10]])

In [ ]:
nc=(c-(np.mean(c)))/np.std(c)
nc

array([[-0.20240846,  0.43812465, -1.41942138,  1.39892432, -0.33051509],
       [ 1.71919087,  0.05380478, -1.41942138,  0.63028458,  0.69433789],
       [ 0.88649783, -0.65078164, -1.41942138,  0.11785809, -0.01024853],
       [-0.07430184,  1.65513756, -1.41942138, -0.13835515,  0.88649783],
       [-0.77888826, -0.58672833, -1.41942138, -0.33051509,  1.71919087]])

In [ ]:
b=np.random.randint(0,36,size=(6,6))
b

array([[26, 10, 21, 17, 24, 32],
       [19, 19, 35, 35,  6, 26],
       [ 9, 32, 17, 15, 26,  8],
       [ 4,  5,  1, 15, 28,  7],
       [ 6, 12, 29,  4, 12, 19],
       [14, 29, 12, 17, 32, 20]])

In [ ]:
t=b[0,:]
l=b[:,0]
r=b[:,5]
d=b[5,:]

borders=np.concatenate((t,l,r,d),axis=0)
borders.reshape(4,6)

array([[26, 10, 21, 17, 24, 32],
       [26, 19,  9,  4,  6, 14],
       [32, 26,  8,  7, 19, 20],
       [14, 29, 12, 17, 32, 20]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a[::-1,::-1]

array([[6, 5, 4],
       [3, 2, 1]])

In [ ]:
n=np.arange(1,51)
n[(n % 15 == 0)]

array([15, 30, 45])

In [ ]:
a1=np.random.randint(1,11,size=(3,3))
print(a1)
a2=np.random.randint(11,21,size=(3,3))
a2

[[ 8 10  1]
 [ 6 10  1]
 [ 3  6  8]]


array([[11, 19, 20],
       [15, 18, 11],
       [20, 17, 18]])

In [ ]:
print(a1*a2)
np.matmul(a1,a2)

[[ 88 190  20]
 [ 90 180  11]
 [ 60 102 144]]


array([[258, 349, 288],
       [236, 311, 248],
       [283, 301, 270]])

In [6]:
m=np.arange(1,6)
print(m)
p=np.random.randint(1,21,size=(4,5))
p

[1 2 3 4 5]


array([[17,  5,  6,  5,  1],
       [ 3, 12,  1,  9, 11],
       [ 4,  3,  9,  3, 15],
       [ 2, 20, 16,  5, 19]])

In [7]:
p-m

array([[16,  3,  3,  1, -4],
       [ 2, 10, -2,  5,  6],
       [ 3,  1,  6, -1, 10],
       [ 1, 18, 13,  1, 14]])

In [12]:
arr=np.random.randint(1,20,size=10000)
arr

val,count=np.unique(arr,return_counts=True)
print(val[np.argmax(count)])

2


In [15]:
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])